### ISSUE TITLE
Kafka Producer Sampler unable to run 

### ISSUE THREAD

**Issue by OcaeanYan** [rollno748/di-kafkameter#12]
Use the same Variable name，but unable to run
Error log：
org.apache.kafka.common.KafkaException: Failed to construct kafka producer
        at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:468)
        at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:291)
        at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:318)
        at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:303)
        at com.di.jmeter.kafka.config.KafkaProducerConfig.testStarted(KafkaProducerConfig.java:81)
        at org.apache.jmeter.engine.StandardJMeterEngine.notifyTestListenersOfStart(StandardJMeterEngine.java:205)
        at org.apache.jmeter.engine.StandardJMeterEngine.run(StandardJMeterEngine.java:382)
        at java.lang.Thread.run(Unknown Source)
Caused by: org.apache.kafka.common.KafkaException: class org.apache.kafka.common.serialization.StringDeserializer is not an instance of org.apache.kafka.common.serialization.Serializer
        at org.apache.kafka.common.config.AbstractConfig.getConfiguredInstance(AbstractConfig.java:405)
        at org.apache.kafka.common.config.AbstractConfig.getConfiguredInstance(AbstractConfig.java:436)
        at org.apache.kafka.common.config.AbstractConfig.getConfiguredInstance(AbstractConfig.java:421)
        at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:386)
        ... 7 more
![image](https://user-images.githubusercontent.com/43510325/224960098-898c8080-3d01-499b-8a06-d2d2965166cf.png)
![image](https://user-images.githubusercontent.com/43510325/224960380-92519916-b374-4f86-97ab-868b094399c9.png)
![image](https://user-images.githubusercontent.com/43510325/224960419-8ee57e29-448d-4aff-8a9d-1b81c3f54843.png)
![image](https://user-images.githubusercontent.com/43510325/224960666-08753ddb-b74a-4cf2-920d-14a4719590cf.png)

**Comment by rollno748** [comment]
Ah right - the issue is due to the serialization class 
try amending the serializer key in producer config to : org.apache.kafka.common.serialization.StringSerializer

and give it a try - if you still see the issue, can you share the jmeter.log file (you can remove the crucial info if something is in there)

**Comment by rollno748** [comment]
I am releasing a newer version (v1.2) of this plugin - which is having the change for default serlializer key and value 
Also with some error handling changes.

Upon your confirmation, I will close this issue

**Comment by OcaeanYan** [comment]
I downloaded version 1.2, but the same problem still occurred. I will send jmeter.log to you

**Comment by OcaeanYan** [comment]
Problem has been solved, thank you
