### ISSUE TITLE
Conflicts with plugin rollno748/Jmeter-pubsub-sampler

### ISSUE THREAD

**Issue by kuboraam** [rollno748/di-kafkameter#5]
I am currently using rollno748/Jmeter-pubsub-sampler to send requests to Pub/Sub and this works well. However, If i have both plugins - rollno748/Jmeter-pubsub-sampler and rollno748/di-kafkameter installed, and I run the same pub/sub test plan, JMeter throws the following stacktrace:

`java.lang.NoSuchMethodError: 'void com.google.common.base.Preconditions.checkArgument(boolean, java.lang.String, int)'
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider$Builder.setPoolSize(InstantiatingGrpcChannelProvider.java:553) ~[jmeter-pubsub-sampler-1.1.jar:?]
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider$Builder.setChannelsPerCpu(InstantiatingGrpcChannelProvider.java:572) ~[jmeter-pubsub-sampler-1.1.jar:?]
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider$Builder.setChannelsPerCpu(InstantiatingGrpcChannelProvider.java:561) ~[jmeter-pubsub-sampler-1.1.jar:?]
	at com.google.cloud.pubsub.v1.Publisher$Builder.<init>(Publisher.java:700) ~[jmeter-pubsub-sampler-1.1.jar:?]
	at com.google.cloud.pubsub.v1.Publisher$Builder.<init>(Publisher.java:651) ~[jmeter-pubsub-sampler-1.1.jar:?]
	at com.google.cloud.pubsub.v1.Publisher.newBuilder(Publisher.java:647) ~[jmeter-pubsub-sampler-1.1.jar:?]
	at com.google.cloud.pubsub.v1.Publisher.newBuilder(Publisher.java:626) ~[jmeter-pubsub-sampler-1.1.jar:?]
	at com.di.jmeter.pubsub.config.PublisherConfig.testStarted(PublisherConfig.java:97) ~[jmeter-pubsub-sampler-1.1.jar:?]
	at org.apache.jmeter.engine.StandardJMeterEngine.notifyTestListenersOfStart(StandardJMeterEngine.java:218) ~[ApacheJMeter_core.jar:5.5]
	at org.apache.jmeter.engine.StandardJMeterEngine.run(StandardJMeterEngine.java:396) ~[ApacheJMeter_core.jar:5.5]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]`

See attached the full trace for your reference.
[jmeter-log-trace.txt](https://github.com/rollno748/di-kafkameter/files/10261670/jmeter-log-trace.txt)

**Comment by rollno748** [comment]
Can you please share the complete jmeter.log and a sample test plan structure of yours ?
I have used both di-kafkameter and pubsub plugin together - haven't faced this.
But there is a possibility of error which might be due to the fatty jar which I am building for di-kafkameter

**Comment by kuboraam** [comment]
Hi, please see attached the full jmeter.log and the sample test plan.

Here is also a list of all the plugins in lib/ext.

```
[user@user-kb-lptp bin]$ ls -la ../lib/ext
total 55888
drwxrwxr-x 2 user user     4096 Dec 21 11:24 .
drwxrwxr-x 4 user user    12288 Feb  1  1980 ..
-rw-r--r-- 1 user user    20224 Feb  1  1980 ApacheJMeter_bolt.jar
-rw-r--r-- 1 user user   764299 Feb  1  1980 ApacheJMeter_components.jar
-rw-r--r-- 1 user user  1853786 Feb  1  1980 ApacheJMeter_core.jar
-rw-r--r-- 1 user user    15246 Feb  1  1980 ApacheJMeter_ftp.jar
-rw-r--r-- 1 user user   119556 Feb  1  1980 ApacheJMeter_functions.jar
-rw-r--r-- 1 user user   528367 Feb  1  1980 ApacheJMeter_http.jar
-rw-r--r-- 1 user user    48143 Feb  1  1980 ApacheJMeter_java.jar
-rw-r--r-- 1 user user    64664 Feb  1  1980 ApacheJMeter_jdbc.jar
-rw-r--r-- 1 user user    96672 Feb  1  1980 ApacheJMeter_jms.jar
-rw-r--r-- 1 user user    21346 Feb  1  1980 ApacheJMeter_junit.jar
-rw-r--r-- 1 user user    49099 Feb  1  1980 ApacheJMeter_ldap.jar
-rw-r--r-- 1 user user    59818 Feb  1  1980 ApacheJMeter_mail.jar
-rw-r--r-- 1 user user    29701 Feb  1  1980 ApacheJMeter_mongodb.jar
-rw-r--r-- 1 user user    14169 Feb  1  1980 ApacheJMeter_native.jar
-rw-r--r-- 1 user user    30531 Feb  1  1980 ApacheJMeter_tcp.jar
-rw-r--r-- 1 user user    10453 Dec 17 06:08 cmdrunner-2.3.jar
-rw-r--r-- 1 user user 12734641 Dec 21 11:24 di-kafkameter-1.0.jar
-rw-r--r-- 1 user user   286235 Dec 17 04:39 gson-2.10.jar
-rw-r--r-- 1 user user   211301 Dec 17 06:08 jmeter-plugins-cmn-jmeter-0.7.jar
-rw-r--r-- 1 user user    11172 Dec 17 06:08 jmeter-plugins-csvars-0.1.jar
-rw-r--r-- 1 user user   906127 Dec 17 06:07 jmeter-plugins-manager-1.8.jar
-rw-r--r-- 1 user user 18493594 Dec 17 04:35 jmeter-pubsub-sampler-1.1.jar
-rw-r--r-- 1 user user   159123 Dec 17 06:08 json-lib-2.4-jdk15.jar
-rw-r--r-- 1 user user 20639119 Dec 12 15:42 pepper-box-1.0.jar
-rw-rw-r-- 1 user user      109 Feb  1  1980 readme.txt
[user@user-kb-lptp bin]$ 

```

[jmeter-ips-redacted.log](https://github.com/rollno748/di-kafkameter/files/10279556/jmeter-ips-redacted.log)
[PubSub-Tester.jmx.txt](https://github.com/rollno748/di-kafkameter/files/10279566/PubSub-Tester.jmx.txt)

**Comment by rollno748** [comment]
Thanks for sharing this - I will take a look at the attached files and push a change if required.

**Comment by rollno748** [comment]
Alright ! - the issue is due to the pub-sub is plugin jar compiled as a shaded jar
I will try to create a plugin and its Transient dependencies separately

**Comment by kuboraam** [comment]
thank you for the prompt response :)

**Comment by rollno748** [comment]
Removed the fatty jar in this new version -1.1 
This should avoid the conflicts with Pubsub plugin

**Comment by rollno748** [comment]
I will close this after releasing this version to plugins manager soon
